# Generated by Django 5.2.5 on 2025-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
