# Generated by Django 5.2.5 on 2025-10-08 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
