# Generated by Django 5.2.5 on 2025-09-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
    ]
