# Generated by Django 5.2.5 on 2025-09-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_cat_image_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descritption',
            new_name='description',
        ),
    ]
