# Generated by Django 5.2.5 on 2025-09-17 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_descritption_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
